# We need to setup different context root for the auth server so that we can store separate
# cookies for both the API gateway as well as the OAuth2 authorization server.
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/  
security:
  user:
    password: password 
# Datasource and JPA configuration to be used for storing the OAuth authorization details 
# and token store
#Client
app:
  client:
    id: mobile-app
    secret: mySecret
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auth-db