server:
  port: 5002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalog-db
feign:
  hystrix:
    enabled: false
item:
  types:
  - product
  - service

item:
  units:
  - 
  name:quantity
  unit:per item
  -
  name:weight
  unit:per kg
  -
  name:time
  unit:per hour
  -
  name:volume
  unit:per litre